# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v1alpha1_component_plugin_config import V1alpha1ComponentPluginConfig  # noqa: E501
from openapi_client.rest import ApiException

class TestV1alpha1ComponentPluginConfig(unittest.TestCase):
    """V1alpha1ComponentPluginConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1ComponentPluginConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v1alpha1_component_plugin_config.V1alpha1ComponentPluginConfig()  # noqa: E501
        if include_optional :
            return V1alpha1ComponentPluginConfig(
                attr = [
                    openapi_client.models.v1alpha1/component_plugin_config/attr.v1alpha1.ComponentPluginConfig.attr()
                    ], 
                build_version = '0', 
                cpu_required = 56, 
                create_time = '0', 
                memory_required = 56, 
                plugin_id = '0', 
                plugin_key = '0', 
                plugin_status = True, 
                service_id = '0', 
                service_meta_type = '0'
            )
        else :
            return V1alpha1ComponentPluginConfig(
                attr = [
                    openapi_client.models.v1alpha1/component_plugin_config/attr.v1alpha1.ComponentPluginConfig.attr()
                    ],
                build_version = '0',
                cpu_required = 56,
                create_time = '0',
                memory_required = 56,
                plugin_id = '0',
                plugin_key = '0',
                plugin_status = True,
                service_id = '0',
                service_meta_type = '0',
        )

    def testV1alpha1ComponentPluginConfig(self):
        """Test V1alpha1ComponentPluginConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
