# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: huangrh@goodrain.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.apps_store_app_version_templete_app_volume import AppsStoreAppVersionTempleteAppVolume  # noqa: E501
from openapi_client.rest import ApiException

class TestAppsStoreAppVersionTempleteAppVolume(unittest.TestCase):
    """AppsStoreAppVersionTempleteAppVolume unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AppsStoreAppVersionTempleteAppVolume
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.apps_store_app_version_templete_app_volume.AppsStoreAppVersionTempleteAppVolume()  # noqa: E501
        if include_optional :
            return AppsStoreAppVersionTempleteAppVolume(
                access_mode = '0', 
                file_content = '0', 
                volume_capacity = 56, 
                volume_name = '0', 
                volume_path = '0', 
                volume_type = '0'
            )
        else :
            return AppsStoreAppVersionTempleteAppVolume(
                access_mode = '0',
                file_content = '0',
                volume_capacity = 56,
                volume_name = '0',
                volume_path = '0',
                volume_type = '0',
        )

    def testAppsStoreAppVersionTempleteAppVolume(self):
        """Test AppsStoreAppVersionTempleteAppVolume"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
