# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.v1alpha1_component import V1alpha1Component  # noqa: E501
from openapi_client.rest import ApiException

class TestV1alpha1Component(unittest.TestCase):
    """V1alpha1Component unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1alpha1Component
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.v1alpha1_component.V1alpha1Component()  # noqa: E501
        if include_optional :
            return V1alpha1Component(
                category = '0', 
                cmd = '0', 
                component_monitor = [
                    openapi_client.models.v1alpha1/component_monitor.v1alpha1.ComponentMonitor(
                        interval = '0', 
                        name = '0', 
                        path = '0', 
                        port = 56, 
                        service_show_name = '0', )
                    ], 
                cpu = 56, 
                dep_service_map_list = [
                    openapi_client.models.v1alpha1/component_dep.v1alpha1.ComponentDep(
                        dep_service_key = '0', )
                    ], 
                deploy_version = '0', 
                extend_method = '0', 
                extend_method_map = openapi_client.models.v1alpha1/component_extend_method_rule.v1alpha1.ComponentExtendMethodRule(
                    is_restart = 56, 
                    max_memory = 56, 
                    max_node = 56, 
                    min_memory = 56, 
                    min_node = 56, 
                    step_memory = 56, 
                    step_node = 56, ), 
                image = '0', 
                language = '0', 
                memory = 56, 
                mnt_relation_list = [
                    openapi_client.models.v1alpha1/component_share_volume.v1alpha1.ComponentShareVolume(
                        mnt_dir = '0', 
                        mnt_name = '0', 
                        service_share_uuid = '0', )
                    ], 
                port_map_list = [
                    openapi_client.models.v1alpha1/component_port.v1alpha1.ComponentPort(
                        container_port = 56, 
                        is_inner_service = True, 
                        is_outer_service = True, 
                        port_alias = '0', 
                        protocol = '0', 
                        tenant_id = '0', )
                    ], 
                probes = [
                    openapi_client.models.v1alpha1/component_probe.v1alpha1.ComponentProbe(
                        id = 56, 
                        cmd = '0', 
                        failure_threshold = 56, 
                        http_header = '0', 
                        initial_delay_second = 56, 
                        is_used = True, 
                        mode = '0', 
                        path = '0', 
                        period_second = 56, 
                        port = 56, 
                        probe_id = '0', 
                        scheme = '0', 
                        service_id = '0', 
                        success_threshold = 56, 
                        timeout_second = 56, )
                    ], 
                service_alias = '0', 
                service_cname = '0', 
                service_connect_info_map_list = [
                    openapi_client.models.v1alpha1/component_env.v1alpha1.ComponentEnv(
                        attr_name = '0', 
                        attr_value = '0', 
                        is_change = True, 
                        name = '0', )
                    ], 
                service_env_map_list = [
                    openapi_client.models.v1alpha1/component_env.v1alpha1.ComponentEnv(
                        attr_name = '0', 
                        attr_value = '0', 
                        is_change = True, 
                        name = '0', )
                    ], 
                service_id = '0', 
                service_image = openapi_client.models.v1alpha1/image_info.v1alpha1.ImageInfo(
                    hub_password = '0', 
                    hub_url = '0', 
                    hub_user = '0', 
                    is_trust = True, 
                    namespace = '0', ), 
                service_key = '0', 
                service_name = '0', 
                service_related_plugin_config = [
                    openapi_client.models.v1alpha1/component_plugin_config.v1alpha1.ComponentPluginConfig(
                        attr = [
                            openapi_client.models.v1alpha1/component_plugin_config/attr.v1alpha1.ComponentPluginConfig.attr()
                            ], 
                        build_version = '0', 
                        cpu_required = 56, 
                        create_time = '0', 
                        memory_required = 56, 
                        plugin_id = '0', 
                        plugin_key = '0', 
                        plugin_status = True, 
                        service_id = '0', 
                        service_meta_type = '0', )
                    ], 
                service_share_uuid = '0', 
                service_source = '0', 
                service_type = '0', 
                service_volume_map_list = [
                    openapi_client.models.v1alpha1/component_volume.v1alpha1.ComponentVolume(
                        access_mode = '0', 
                        file_content = '0', 
                        sharing_policy = '0', 
                        volume_capacity = 56, 
                        volume_name = '0', 
                        volume_path = '0', 
                        volume_type = '0', )
                    ], 
                share_image = '0', 
                share_type = '0', 
                version = '0'
            )
        else :
            return V1alpha1Component(
                category = '0',
                cmd = '0',
                component_monitor = [
                    openapi_client.models.v1alpha1/component_monitor.v1alpha1.ComponentMonitor(
                        interval = '0', 
                        name = '0', 
                        path = '0', 
                        port = 56, 
                        service_show_name = '0', )
                    ],
                cpu = 56,
                dep_service_map_list = [
                    openapi_client.models.v1alpha1/component_dep.v1alpha1.ComponentDep(
                        dep_service_key = '0', )
                    ],
                deploy_version = '0',
                extend_method = '0',
                extend_method_map = openapi_client.models.v1alpha1/component_extend_method_rule.v1alpha1.ComponentExtendMethodRule(
                    is_restart = 56, 
                    max_memory = 56, 
                    max_node = 56, 
                    min_memory = 56, 
                    min_node = 56, 
                    step_memory = 56, 
                    step_node = 56, ),
                image = '0',
                language = '0',
                memory = 56,
                mnt_relation_list = [
                    openapi_client.models.v1alpha1/component_share_volume.v1alpha1.ComponentShareVolume(
                        mnt_dir = '0', 
                        mnt_name = '0', 
                        service_share_uuid = '0', )
                    ],
                port_map_list = [
                    openapi_client.models.v1alpha1/component_port.v1alpha1.ComponentPort(
                        container_port = 56, 
                        is_inner_service = True, 
                        is_outer_service = True, 
                        port_alias = '0', 
                        protocol = '0', 
                        tenant_id = '0', )
                    ],
                probes = [
                    openapi_client.models.v1alpha1/component_probe.v1alpha1.ComponentProbe(
                        id = 56, 
                        cmd = '0', 
                        failure_threshold = 56, 
                        http_header = '0', 
                        initial_delay_second = 56, 
                        is_used = True, 
                        mode = '0', 
                        path = '0', 
                        period_second = 56, 
                        port = 56, 
                        probe_id = '0', 
                        scheme = '0', 
                        service_id = '0', 
                        success_threshold = 56, 
                        timeout_second = 56, )
                    ],
                service_alias = '0',
                service_cname = '0',
                service_connect_info_map_list = [
                    openapi_client.models.v1alpha1/component_env.v1alpha1.ComponentEnv(
                        attr_name = '0', 
                        attr_value = '0', 
                        is_change = True, 
                        name = '0', )
                    ],
                service_env_map_list = [
                    openapi_client.models.v1alpha1/component_env.v1alpha1.ComponentEnv(
                        attr_name = '0', 
                        attr_value = '0', 
                        is_change = True, 
                        name = '0', )
                    ],
                service_id = '0',
                service_image = openapi_client.models.v1alpha1/image_info.v1alpha1.ImageInfo(
                    hub_password = '0', 
                    hub_url = '0', 
                    hub_user = '0', 
                    is_trust = True, 
                    namespace = '0', ),
                service_key = '0',
                service_name = '0',
                service_source = '0',
                service_type = '0',
                service_volume_map_list = [
                    openapi_client.models.v1alpha1/component_volume.v1alpha1.ComponentVolume(
                        access_mode = '0', 
                        file_content = '0', 
                        sharing_policy = '0', 
                        volume_capacity = 56, 
                        volume_name = '0', 
                        volume_path = '0', 
                        volume_type = '0', )
                    ],
                share_image = '0',
                version = '0',
        )

    def testV1alpha1Component(self):
        """Test V1alpha1Component"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
