# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.platform_open_api import PlatformOpenApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPlatformOpenApi(unittest.TestCase):
    """PlatformOpenApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.platform_open_api.PlatformOpenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_healthz(self):
        """Test case for check_healthz

        检查应用市场的是否运行中  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
