# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: huangrh@goodrain.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.apps_store_app_version_templete_app_extend_method_rule import AppsStoreAppVersionTempleteAppExtendMethodRule  # noqa: E501
from openapi_client.rest import ApiException

class TestAppsStoreAppVersionTempleteAppExtendMethodRule(unittest.TestCase):
    """AppsStoreAppVersionTempleteAppExtendMethodRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AppsStoreAppVersionTempleteAppExtendMethodRule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.apps_store_app_version_templete_app_extend_method_rule.AppsStoreAppVersionTempleteAppExtendMethodRule()  # noqa: E501
        if include_optional :
            return AppsStoreAppVersionTempleteAppExtendMethodRule(
                is_restart = 56, 
                max_memory = 56, 
                max_node = 56, 
                min_memory = 56, 
                min_node = 56, 
                step_memory = 56, 
                step_node = 56
            )
        else :
            return AppsStoreAppVersionTempleteAppExtendMethodRule(
                is_restart = 56,
                max_memory = 56,
                max_node = 56,
                min_memory = 56,
                min_node = 56,
                step_memory = 56,
                step_node = 56,
        )

    def testAppsStoreAppVersionTempleteAppExtendMethodRule(self):
        """Test AppsStoreAppVersionTempleteAppExtendMethodRule"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
