# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: huangrh@goodrain.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.registry_api_api import RegistryApiApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRegistryApiApi(unittest.TestCase):
    """RegistryApiApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.registry_api_api.RegistryApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_do_auth(self):
        """Test case for do_auth

        image registry auth server  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
