# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: huangrh@goodrain.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V1BindableMarket(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'desc': 'str',
        'domain': 'str',
        'logo': 'str',
        'name': 'str',
        'url': 'str'
    }

    attribute_map = {
        'desc': 'desc',
        'domain': 'domain',
        'logo': 'logo',
        'name': 'name',
        'url': 'url'
    }

    def __init__(self, desc=None, domain=None, logo=None, name=None, url=None, local_vars_configuration=None):  # noqa: E501
        """V1BindableMarket - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._desc = None
        self._domain = None
        self._logo = None
        self._name = None
        self._url = None
        self.discriminator = None

        self.desc = desc
        self.domain = domain
        self.logo = logo
        self.name = name
        self.url = url

    @property
    def desc(self):
        """Gets the desc of this V1BindableMarket.  # noqa: E501

        商店简介  # noqa: E501

        :return: The desc of this V1BindableMarket.  # noqa: E501
        :rtype: str
        """
        return self._desc

    @desc.setter
    def desc(self, desc):
        """Sets the desc of this V1BindableMarket.

        商店简介  # noqa: E501

        :param desc: The desc of this V1BindableMarket.  # noqa: E501
        :type desc: str
        """
        if self.local_vars_configuration.client_side_validation and desc is None:  # noqa: E501
            raise ValueError("Invalid value for `desc`, must not be `None`")  # noqa: E501

        self._desc = desc

    @property
    def domain(self):
        """Gets the domain of this V1BindableMarket.  # noqa: E501

        商店域  # noqa: E501

        :return: The domain of this V1BindableMarket.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this V1BindableMarket.

        商店域  # noqa: E501

        :param domain: The domain of this V1BindableMarket.  # noqa: E501
        :type domain: str
        """
        if self.local_vars_configuration.client_side_validation and domain is None:  # noqa: E501
            raise ValueError("Invalid value for `domain`, must not be `None`")  # noqa: E501

        self._domain = domain

    @property
    def logo(self):
        """Gets the logo of this V1BindableMarket.  # noqa: E501

        商店 Logo  # noqa: E501

        :return: The logo of this V1BindableMarket.  # noqa: E501
        :rtype: str
        """
        return self._logo

    @logo.setter
    def logo(self, logo):
        """Sets the logo of this V1BindableMarket.

        商店 Logo  # noqa: E501

        :param logo: The logo of this V1BindableMarket.  # noqa: E501
        :type logo: str
        """
        if self.local_vars_configuration.client_side_validation and logo is None:  # noqa: E501
            raise ValueError("Invalid value for `logo`, must not be `None`")  # noqa: E501

        self._logo = logo

    @property
    def name(self):
        """Gets the name of this V1BindableMarket.  # noqa: E501

        商店名  # noqa: E501

        :return: The name of this V1BindableMarket.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1BindableMarket.

        商店名  # noqa: E501

        :param name: The name of this V1BindableMarket.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def url(self):
        """Gets the url of this V1BindableMarket.  # noqa: E501

        通信地址  # noqa: E501

        :return: The url of this V1BindableMarket.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this V1BindableMarket.

        通信地址  # noqa: E501

        :param url: The url of this V1BindableMarket.  # noqa: E501
        :type url: str
        """
        if self.local_vars_configuration.client_side_validation and url is None:  # noqa: E501
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1BindableMarket):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1BindableMarket):
            return True

        return self.to_dict() != other.to_dict()
