# coding: utf-8

"""
    app-server

    Resource for managing app-server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V1alpha1ComponentMonitor(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'interval': 'str',
        'name': 'str',
        'path': 'str',
        'port': 'int',
        'service_show_name': 'str'
    }

    attribute_map = {
        'interval': 'interval',
        'name': 'name',
        'path': 'path',
        'port': 'port',
        'service_show_name': 'service_show_name'
    }

    def __init__(self, interval=None, name=None, path=None, port=None, service_show_name=None, local_vars_configuration=None):  # noqa: E501
        """V1alpha1ComponentMonitor - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._interval = None
        self._name = None
        self._path = None
        self._port = None
        self._service_show_name = None
        self.discriminator = None

        self.interval = interval
        self.name = name
        self.path = path
        self.port = port
        self.service_show_name = service_show_name

    @property
    def interval(self):
        """Gets the interval of this V1alpha1ComponentMonitor.  # noqa: E501


        :return: The interval of this V1alpha1ComponentMonitor.  # noqa: E501
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this V1alpha1ComponentMonitor.


        :param interval: The interval of this V1alpha1ComponentMonitor.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and interval is None:  # noqa: E501
            raise ValueError("Invalid value for `interval`, must not be `None`")  # noqa: E501

        self._interval = interval

    @property
    def name(self):
        """Gets the name of this V1alpha1ComponentMonitor.  # noqa: E501


        :return: The name of this V1alpha1ComponentMonitor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1alpha1ComponentMonitor.


        :param name: The name of this V1alpha1ComponentMonitor.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def path(self):
        """Gets the path of this V1alpha1ComponentMonitor.  # noqa: E501


        :return: The path of this V1alpha1ComponentMonitor.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this V1alpha1ComponentMonitor.


        :param path: The path of this V1alpha1ComponentMonitor.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and path is None:  # noqa: E501
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def port(self):
        """Gets the port of this V1alpha1ComponentMonitor.  # noqa: E501


        :return: The port of this V1alpha1ComponentMonitor.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this V1alpha1ComponentMonitor.


        :param port: The port of this V1alpha1ComponentMonitor.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and port is None:  # noqa: E501
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def service_show_name(self):
        """Gets the service_show_name of this V1alpha1ComponentMonitor.  # noqa: E501


        :return: The service_show_name of this V1alpha1ComponentMonitor.  # noqa: E501
        :rtype: str
        """
        return self._service_show_name

    @service_show_name.setter
    def service_show_name(self, service_show_name):
        """Sets the service_show_name of this V1alpha1ComponentMonitor.


        :param service_show_name: The service_show_name of this V1alpha1ComponentMonitor.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and service_show_name is None:  # noqa: E501
            raise ValueError("Invalid value for `service_show_name`, must not be `None`")  # noqa: E501

        self._service_show_name = service_show_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1ComponentMonitor):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1ComponentMonitor):
            return True

        return self.to_dict() != other.to_dict()
